### ISSUE TITLE
Failed to find module

### ISSUE THREAD

**Issue by irthos** [NathanaelA/nativescript-orientation#23]
Hi, appreciate that you're working on this repo. IMO it should be a part of Nativescript core.
I'm running Node 9.2 with Nativescript 3, with https://github.com/tralves/nativescript-vue-webpack-template.

My Code:
```
import Vue from 'nativescript-vue'
import App from './components/App.vue'
import Orientation from 'nativescript-orientation'
import Vuex from 'vuex'
import Router from 'vue-router'
import Physics from 'nativescript-physics-js'

new Vue({
    render: h => h('app'),
    components: {
        App
    },
    mounted() {
    	Orientation.setOrientation('landscape');
    	Orientation.disableRotation();
    }
}).$start();
```

Error on Android Emulator
``` 
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-orientation", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
    android.app.ActivityThread.-wrap1(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
    android.os.Handler.dispatchMessage(Handler.java:105)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/app.js', line: 6, column: 35
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-orientation", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
    android.app.ActivityThread.-wrap1(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
    android.os.Handler.dispatchMessage(Handler.java:105)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/app.js', line: 6, column: 35
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5794)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "nativescript-orientation", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
    android.app.ActivityThread.-wrap1(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
    android.os.Handler.dispatchMessage(Handler.java:105)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/app.js', line: 6, column: 35
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "nativescript-orientation", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
    android.app.ActivityThread.-wrap1(Unknown Source:0)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
    android.os.Handler.dispatchMessage(Handler.java:105)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/app.js', line: 6, column: 35
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:530)
	at com.tns.Runtime.run(Runtime.java:522)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
	... 8 more
```
Error on iOS
```
Project successfully built.
Installing...
Successfully installed on device with identifier '0C285A6A-CE36-4D75-8122-D933CEC7F193'.
Successfully transferred all files.
Refreshing application...
Successfully synced application org.nativescript.nativescriptvuewebpack on device 0C285A6A-CE36-4D75-8122-D933CEC7F193.
Preparing project...
Project successfully prepared (iOS)
Successfully transferred app.css.
Successfully transferred app.js.
Refreshing application...
Successfully synced application org.nativescript.nativescriptvuewebpack on device 0C285A6A-CE36-4D75-8122-D933CEC7F193.
1   0x109235bc8 -[TNSRuntime executeModule:referredBy:]
2   0x108d17c71 main
3   0x10c06bd81 start
file:///app/app.js:6:42: JS ERROR Error: Could not find module 'nativescript-orientation'. Computed path '/Users/i/Library/Developer/CoreSimulator/Devices/0C285A6A-CE36-4D75-8122-D933CEC7F193/data/Containers/Bundle/Application/D0389E9B-0769-47CC-B7A4-F9BB2596F36D/tns.app/app/tns_modules/nativescript-orientation'.
```

**Comment by irthos** [comment]
part of the problem was me using `npm install` instead of `tns plugin add`. iOS works, ish.. I see a more specific issue for Android on line 86, starting col. 38. 

I'm wondering if it has to do with a fn closure in that timeout()?

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method run failed

TypeError: Cannot read property 'setOrientation' of undefined
File: "file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-orientation/orientation.js, line: 86, column: 38

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-orientation/orientation.js', line: 86, column: 39
	Frame: function:'invoke', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'run', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

I tried removing the function wrapper and that yields a new error on Android while iOS breaks functionality. Worth noting that iOS disableRotation still works.

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.nativescriptvuewebpack/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'setOrientation' of undefined
File: "file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-vue/dist/index.js, line: 532, column: 6

StackTrace: 
	Frame: function:'orientation.setOrientation', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-orientation/orientation.js', line: 86, column: 26
	Frame: function:'mounted', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/app.js', line: 44, column: 21
	Frame: function:'callHook', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3580, column: 21
	Frame: function:'mountComponent', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3474, column: 5
	Frame: function:'create', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9034, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 72, column: 22
	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 123, column: 16
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 191, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 589, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'setOrientation' of undefined
File: "file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-vue/dist/index.js, line: 532, column: 6

StackTrace: 
	Frame: function:'orientation.setOrientation', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-orientation/orientation.js', line: 86, column: 26
	Frame: function:'mounted', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/app.js', line: 44, column: 21
	Frame: function:'callHook', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3580, column: 21
	Frame: function:'mountComponent', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3474, column: 5
	Frame: function:'create', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9034, column: 9
	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 72, column: 22
	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 123, column: 16
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 191, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 589, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6975)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
	... 9 more

**Comment by irthos** [comment]
I'll close this issue, as we can now find the module. I'll open a different one for the race condition.
