### ISSUE TITLE
TypeError: Cannot read property 'setOrientation' of undefined

### ISSUE THREAD

**Issue by irthos** [NathanaelA/nativescript-orientation#24]
Using https://github.com/tralves/nativescript-vue-webpack-template, orientation is undefined. 

I hacked it to work (bottom code) by requiring 'application' then setting a timeout to 2000 with setOrientation. Setting Timeout to 0 works for android but iOS misses the call.

Original code that brings error.
``` 
import Vue from 'nativescript-vue'
import App from './components/App.vue'
import orientation from 'nativescript-orientation'
import Vuex from 'vuex'
import Router from 'vue-router'
import Physics from 'nativescript-physics-js'

new Vue({
    render: h => h('app'),
    components: {
        App
    },
    mounted() {
    	orientation.setOrientation('landscape');
        orientation.disableRotation();
    }
}).$start();
```

Error:
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method run failed

TypeError: Cannot read property 'setOrientation' of undefined
File: "file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-orientation/orientation.js, line: 86, column: 38

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/nativescript-orientation/orientation.js', line: 86, column: 39
	Frame: function:'invoke', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'run', file:'file:///data/data/org.nativescript.nativescriptvuewebpack/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

```

Hack to make things work:
``` 
const application = require('application')
import Vue from 'nativescript-vue'
import App from './components/App.vue'
import orientation from 'nativescript-orientation'
import Vuex from 'vuex'
import Router from 'vue-router'
import Physics from 'nativescript-physics-js'

setTimeout(()=>{
	orientation.setOrientation('landscape');
	orientation.disableRotation();
}, 2000)

new Vue({
    render: h => h('app'),
    components: {
        App
    },
    mounted() {
    	*/orientation.setOrientation('landscape');
        orientation.disableRotation();*/
    }
}).$start();
```

**Comment by elvismercado** [comment]
I am also seeing this phenomenon, but only when i build with the --snapshot option for android

**Comment by NathanaelA** [comment]
This will be fixed in the version that should be released later today.  Thanks for the report!
