### ISSUE TITLE
TypeError: page._refreshCss is not a function when require nativescript-orientation

### ISSUE THREAD

**Issue by neigaard** [NathanaelA/nativescript-orientation#32]
I have added nativescript-orientation to a Angular shared project created with the nativescript/schematics, but when I add the "require( 'nativescript-orientation'
);" to my "app-module.tns.ts" I get the following error (you can see the project here https://www.dropbox.com/s/69hmhfkx7k8coot/oxon.zip?dl=0):

An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onViewAttachedToWindow failed

TypeError: page._refreshCss is not a function
File: "file:///data/data/org.nativescript.oxon/files/app/vendor.js, line: 65916, column: 6

StackTrace: 
	Frame: function:'applyOrientationToPage', file:'file:///data/data/org.nativescript.oxon/files/app/vendor.js', line: 65916, column: 7
	Frame: function:'handleNavigatingTo', file:'file:///data/data/org.nativescript.oxon/files/app/vendor.js', line: 65946, column: 3
	Frame: function:'runEvent', file:'file:///data/data/org.nativescript.oxon/files/app/vendor.js', line: 65120, column: 28
	Frame: function:'', file:'file:///data/data/org.nativescript.oxon/files/app/vendor.js', line: 65173, column: 9
	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase._onNavigatingTo', file:'file:///data/data/org.nativescript.oxon/files/app/vendor.js', line: 98987, column: 37
	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase.performNavigation', file:'file:///data/data/org.nativescript.oxon/files/app/vendor.js', line: 98959, column: 14
	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame-common.js.FrameBase._processNextNavigationEntry', file:'file:///data/data/org.nativescript.oxon/files/app/vendor.js', line: 98952, column: 22
	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.Frame._processNextNavigationEntry', file:'file:///data/data/org.nativescript.oxon/files/app/vendor.js', line: 99399, column: 58
	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.Frame._onAttachedToWindow', file:'file:///data/data/org.nativescript.oxon/files/app/vendor.js', line: 99375, column: 14
	Frame: function:'AttachListener.onViewAttachedToWindow', file:'file:///data/data/org.nativescript.oxon/files/app/vendor.js', line: 99299, column: 27

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
	at com.tns.Runtime.callJSMethod(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:954)
	at com.tns.Runtime.callJSMethod(Runtime.java:946)
	at com.tns.gen.java.lang.Object_vendor_99293_36_AttachListener.onViewAttachedToWindow(Object_vendor_99293_36_AttachListener.java:17)
	at android.view.View.dispatchAttachedToWindow(View.java:17456)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3326)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3333)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1668)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by neigaard** [comment]
Oh my bad, I used a old version. Sorry.
