### ISSUE TITLE
disableRotation() doesn't work in Android, in iOS it makes the background image flicker

### ISSUE THREAD

**Issue by sudhanshu-15** [NathanaelA/nativescript-orientation#5]
I am trying to enforce disable rotation app wide. I installed the plugin and added the following code in my app.ts
```
var orientation = require('nativescript-orientation');
  orientation.disableRotation();
```
But on android the app is crashing and giving me an error:
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

TypeError: Cannot read property 'disableRotation' of undefined
File: "file:///data/data/org.sunapsis.iommobile/files/app/tns_modules/nativescript-orientation/orientation.js, line: 60, column: 34

StackTrace: 
	Frame: function:'orientation.disableRotation', file:'file:///data/data/org.sunapsis.iommobile/files/app/tns_modules/nativescript-orientation/orientation.js', line: 60, column: 35
	Frame: function:'', file:'file:///data/data/org.sunapsis.iommobile/files/app/app.js', line: 17, column: 13
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'disableRotation' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'orientation.disableRotation', file:'file:///data/data/org.sunapsis.iommobile/files/app/tns_modules/nativescript-orientation/orientation.js', line: 60, column: 35
	Frame: function:'', file:'file:///data/data/org.sunapsis.iommobile/files/app/app.js', line: 17, column: 13
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4747)
	at android.app.ActivityThread.-wrap1(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1418)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

TypeError: Cannot read property 'disableRotation' of undefined
File: "file:///data/data/org.sunapsis.iommobile/files/app/tns_modules/nativescript-orientation/orientation.js, line: 60, column: 34

StackTrace: 
	Frame: function:'orientation.disableRotation', file:'file:///data/data/org.sunapsis.iommobile/files/app/tns_modules/nativescript-orientation/orientation.js', line: 60, column: 35
	Frame: function:'', file:'file:///data/data/org.sunapsis.iommobile/files/app/app.js', line: 17, column: 13
	Frame: function:'require', file:'', line: 1, column: 266


TypeError: Cannot read property 'disableRotation' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'orientation.disableRotation', file:'file:///data/data/org.sunapsis.iommobile/files/app/tns_modules/nativescript-orientation/orientation.js', line: 60, column: 35
	Frame: function:'', file:'file:///data/data/org.sunapsis.iommobile/files/app/app.js', line: 17, column: 13
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:580)
	at com.tns.Runtime.run(Runtime.java:574)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4744)
	... 8 more
```

Moreover the same thing is working fine in iOS, but the background image flickers and turns white for few secs on rotating the device.

Is there a way to enforce a app wide orientation?

**Comment by NathanaelA** [comment]
I have fixed that issue and published 1.5.5, thanks for the bug report.
